"""``cases``, ``archive`` and ``build``: generator → ``cases/*.in`` + ``init.yml`` → ``.zip``.

The generator is the author's code (``<problem>/generator.py``); this module is
the fixed half of the contract (decision Q22).  The protocol:

* ``TestCase.check()`` / ``TestCase.write_file(f)`` -- the case validates itself
  and writes its own input format.  The *toolkit* chooses file names.
* ``Generator.get_cases()`` -- the ordered case list.  Position is file number:
  case ``i`` is ``cases/{i}.in`` / ``cases/{i}.out``.
* ``Generator.get_subtasks()`` -- ``(points, check_fn)`` per subtask, with an
  optional third element: a list of 1-based prerequisite batch numbers, which
  becomes DMOJ's per-batch ``dependencies:`` key.  Two-element tuples keep
  working unchanged.

A case belongs to a subtask when ``check_fn(case)`` is truthy, so a case may be
in several batches -- that is the "all-accepting final subtask" convention the
``standard``/``batched`` templates rely on.

Two things the emitted ``init.yml`` gets from ``meta.yml`` instead of from the
generator (both are properties of the *model*, resolved by :mod:`meta`):

* ``submission: text`` models (the two output-only ones) have **no input**:
  DMOJ's ``TestCase._make_input_data_io()`` falls back to a sealed empty
  ``MemoryIO`` when a case declares no ``in:`` (``dmoj/problem.py:489-493``), so
  those cases declare only ``out:`` and their ``write_file`` is never called.
* a custom-checker model needs ``checker.py`` on disk, and a signature model
  needs ``evaluator.cpp`` + ``signature.hpp``; both are named in ``init.yml``
  and both are checked here, so a dangling reference is an authoring error
  instead of a judge-side failure inside the container.

Batches are validated the way DMOJ validates them
(``dmoj/problem.py:325-337``): dependencies must be positive integers strictly
less than the batch number that declares them, nested batches are rejected
outright (``InvalidInitException('nested batches')``), and a batch that selects
no case is refused here because an empty ``batched:`` key is YAML ``null`` and
the judge iterates that value.

The archive is written *reproducibly* -- fixed member timestamps, sorted
membership, pinned permissions and compression level (:func:`write_reproducible_zip`)
-- so that a checksum committed beside it survives a fresh clone.  Two checksums
are written on every archive (decision Q15): the SHA-256 of the archive bytes and
an independent SHA-256 manifest of the case *data*, so an unrelated repackaging
cannot masquerade as a change in the cases (or the reverse).
"""

from __future__ import annotations

import argparse
import dataclasses
import hashlib
import io
import json
import re
import shutil
import types
import zipfile
from collections.abc import Callable, Iterable, Mapping, Sequence
from pathlib import Path
from typing import Any, Protocol

import yaml

from . import judges
from . import meta as meta_mod
from .commands import Command, register
from .errors import CaseError

GENERATOR_FILENAME = "generator.py"
INIT_FILENAME = "init.yml"
CASES_DIRNAME = "cases"

#: The standard checker/signature file names (ticket 11 fixes these names; the
#: judge accepts others, but a problem that renames them must be checked here
#: rather than emitting a reference to a file that does not exist).
CHECKER_FILENAME = "checker.py"
SIGNATURE_HEADER = "signature.hpp"
SIGNATURE_ENTRY = "evaluator.cpp"

#: First line of every generated ``init.yml``.  It is a build artifact: the
#: sources of truth are ``meta.yml`` (model/limits) and ``generator.py`` (cases).
INIT_HEADER = (
    "# Generated by `problemsetting cases` -- edit meta.yml and generator.py, not this file."
)

#: Leftover case files from a previous, larger run are removed: a stale
#: ``cases/{i}.out`` is the one failure mode this toolkit must never leave
#: behind, because the judge would grade it as the expected answer.
_CASE_FILE_RE = re.compile(r"(\d+)\.(?:in|out)\Z")


class GeneratorLike(Protocol):
    """The slice of the author's ``Generator`` this module calls.

    Structural, not inherited: a generator is author code loaded from a file, so
    there is no base class to subclass and nothing to enforce at runtime -- only
    the two calls below, which :func:`load_generator` and :func:`read_cases` /
    :func:`read_subtasks` check for by hand.
    """

    def get_cases(self) -> Sequence[Any]: ...

    def get_subtasks(self) -> Sequence[Any]: ...


# ---------------------------------------------------------------------------
# The generator: loading it, and reading the protocol out of it
# ---------------------------------------------------------------------------


def load_generator(problem_dir: Path, seed: int | None = None) -> GeneratorLike:
    """Compile and run ``<problem_dir>/generator.py``; instantiate its ``Generator``.

    The file is *compiled from source each time*, never imported through
    ``importlib``'s file loader: that loader honours a sibling ``__pycache__``
    entry whenever the bytecode's recorded (mtime, size) still matches, so a
    same-second, same-length edit would silently run the previous generator --
    and the cases would then be built from code the author is no longer looking
    at.  Compiling costs nothing at this scale and removes the whole class of
    "why did my change not apply" bugs.
    """
    path = problem_dir / GENERATOR_FILENAME
    if not path.is_file():
        raise CaseError(
            f"{path} not found -- every problem needs a generator.py; the model "
            f"template ships a complete one to start from"
        )
    try:
        code = compile(path.read_text(encoding="utf-8"), str(path), "exec")
    except (OSError, UnicodeDecodeError, SyntaxError) as error:
        raise CaseError(f"{path}: {error}") from error

    module = types.ModuleType(f"_problemsetting_generator_{problem_dir.name}")
    module.__file__ = str(path)
    try:
        exec(code, module.__dict__)
    except Exception as error:  # author code: report it without the traceback
        raise CaseError(f"{path}: {error}") from error

    factory = getattr(module, "Generator", None)
    if factory is None:
        raise CaseError(
            f"{path}: no `Generator` class -- the toolkit instantiates "
            f"`Generator()` and calls `get_cases()` and `get_subtasks()` on it"
        )
    try:
        return factory() if seed is None else factory(seed)
    except Exception as error:
        raise CaseError(f"{path}: Generator(...) failed: {error}") from error


@dataclasses.dataclass(frozen=True)
class Subtask:
    """One entry of ``Generator.get_subtasks()`` after validation."""

    #: 1-based batch number, i.e. the order in ``get_subtasks()``.
    number: int
    points: int | float
    check: Callable[[Any], Any]
    #: Prerequisite batch numbers; empty when the subtask declares none.
    dependencies: tuple[int, ...]


def require_sequence(value: Any, source: str, expectation: str) -> Sequence[Any]:
    """Check ``value`` is a list-shaped result; ``expectation`` names what it should be.

    ``str``/``bytes`` are sequences too, and a generator that returns
    ``"cases"`` by mistake would otherwise be read as three one-character cases.
    """
    if isinstance(value, (str, bytes)) or not isinstance(value, Sequence):
        raise CaseError(f"{source}: {expectation}, not {type(value).__name__}")
    return value


def read_cases(generator: GeneratorLike, source: str) -> list[Any]:
    """``generator.get_cases()``, validated as a non-empty ordered sequence."""
    try:
        cases = generator.get_cases()
    except Exception as error:  # the author's ``check()`` runs here
        raise CaseError(f"{source}: get_cases() failed: {error}") from error
    require_sequence(cases, source, "get_cases() must return a list of cases")
    if not cases:
        raise CaseError(f"{source}: get_cases() returned no cases; there is nothing to grade")
    for index, case in enumerate(cases):
        for method in ("check", "write_file"):
            if not callable(getattr(case, method, None)):
                raise CaseError(
                    f"{source}: case {index} ({type(case).__name__}) has no "
                    f"{method}() method; the toolkit only requires those two"
                )
    return list(cases)


def read_subtasks(generator: GeneratorLike, source: str) -> list[Subtask]:
    """``generator.get_subtasks()``, validated against DMOJ's batch rules.

    Every rule here exists because the alternative is an ``init.yml`` the judge
    rejects at load time with a message about the file's shape rather than about
    the generator line that caused it.
    """
    try:
        entries = generator.get_subtasks()
    except Exception as error:
        raise CaseError(f"{source}: get_subtasks() failed: {error}") from error
    require_sequence(entries, source, "get_subtasks() must return a list of (points, check) entries")
    if not entries:
        raise CaseError(
            f"{source}: get_subtasks() returned nothing; a problem with no subtasks "
            f"has nothing to grade"
        )

    subtasks: list[Subtask] = []
    for index, entry in enumerate(entries, start=1):
        subtasks.append(_read_subtask(entry, index, source, len(entries)))
    return subtasks


def _read_subtask(entry: Any, number: int, source: str, total: int) -> Subtask:
    where = f"subtask {number} of {total}" if total > 1 else "the subtask"
    require_sequence(entry, source, f"{where} must be a (points, check) pair")
    if len(entry) not in (2, 3):
        raise CaseError(
            f"{source}: {where} has {len(entry)} elements; expected (points, check) "
            f"or (points, check, dependencies)"
        )
    if not isinstance(entry[1], Callable):
        if isinstance(entry[1], (list, tuple)):
            # The shape this rejects: (points, [inner, batches]).
            raise CaseError(
                f"{source}: {where} holds a nested subtask list where the classifier "
                f"should be; DMOJ rejects nested batches ('nested batches'), so "
                f"subtasks must be a flat list of (points, check) pairs"
            )
        raise CaseError(
            f"{source}: {where} has a non-callable classifier ({entry[1]!r}); the second "
            f"element is `check_fn(case)`, called once per case"
        )

    points = entry[0]
    if isinstance(points, bool) or not isinstance(points, (int, float)):
        raise CaseError(
            f"{source}: {where} has non-numeric points ({points!r}); points are the "
            f"batch's share of the score"
        )
    if points <= 0:
        raise CaseError(
            f"{source}: {where} is worth {points} points; a batch worth no points can "
            f"never score"
        )

    dependencies = _read_dependencies(entry[2] if len(entry) == 3 else [], number, where, source)
    return Subtask(number, points, entry[1], dependencies)


def _read_dependencies(raw: Any, number: int, where: str, source: str) -> tuple[int, ...]:
    if raw is None:
        return ()
    require_sequence(
        raw,
        source,
        f"{where} declares dependencies {raw!r}; the third element must be a "
        f"list of 1-based batch numbers, e.g. [1]",
    )
    dependencies: list[int] = []
    for value in raw:
        if isinstance(value, bool) or not isinstance(value, int):
            raise CaseError(
                f"{source}: {where} declares dependency {value!r}; dependencies must be "
                f"positive integers naming earlier batches"
            )
        if value < 1:
            raise CaseError(
                f"{source}: {where} depends on batch {value}; DMOJ requires batches to "
                f"be positive integers ('dependencies must be positive integers')"
            )
        if value >= number:
            raise CaseError(
                f"{source}: {where} depends on batch {value}, which is not an earlier "
                f"batch; DMOJ requires each dependency to be less than the batch that "
                f"declares it ('dependencies depends on non-earlier batch')"
            )
        dependencies.append(value)
    # Sorted and deduplicated: the judge compares dependencies as a set, so this
    # only makes the emitted file canonical.
    return tuple(sorted(set(dependencies)))


def classify(subtasks: Iterable[Subtask], cases: Sequence[Any], source: str) -> list[list[int]]:
    """Case indices per subtask, in case order.

    Two rules, both of which exist because the alternative is an ``init.yml``
    the judge chokes on at load time instead of an error naming the generator:

    * ``check_fn`` is author code, so a classifier that raises is reported with
      the batch and the case it raised on;
    * a batch that selects no case is refused.  DMOJ branches on
      ``'batched' in case_config`` and then iterates the value
      (``dmoj/problem.py:227-235``), so an empty ``batched:`` key -- YAML
      ``null`` -- fails with ``TypeError: 'NoneType' object is not iterable``.
    """
    cases = list(cases)
    membership: list[list[int]] = []
    for subtask in subtasks:
        selected: list[int] = []
        for index, case in enumerate(cases):
            try:
                matched = subtask.check(case)
            except Exception as error:
                raise CaseError(
                    f"{source}: the classifier of batch {subtask.number} raised on case "
                    f"{index}: {error}"
                ) from error
            if matched:
                selected.append(index)
        if not selected:
            raise CaseError(
                f"{source}: the classifier of batch {subtask.number} selects none of the "
                f"{len(cases)} cases; a batch with no cases cannot be emitted (DMOJ would "
                f"fail to load the problem).  Every batch needs at least one case -- the "
                f"usual shape is an all-accepting last batch that absorbs the rest"
            )
        membership.append(selected)
    return membership


# ---------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class CaseFile:
    """Where one case's files live, relative to the problem directory."""

    index: int
    has_input: bool

    @property
    def input_name(self) -> str | None:
        return f"{CASES_DIRNAME}/{self.index}.in" if self.has_input else None

    @property
    def output_name(self) -> str:
        return f"{CASES_DIRNAME}/{self.index}.out"


def write_case_files(
    problem_dir: Path, cases: Sequence[Any], *, has_input: bool, source: str
) -> tuple[list[CaseFile], list[str]]:
    """Write each case's input; return its file names and the outputs invalidated.

    Expected outputs are *not* produced here: they are ``outputs``' job (ticket
    03), because they require running the model solution.  But an input that
    *changed* invalidates its sibling ``.out``, which is deleted so that the pair
    cannot silently disagree.  A stale ``.out`` is the one failure mode this
    toolkit must never ship, because the judge would grade it as the expected
    answer.  An input that is byte-identical is left alone, so re-running with no
    change keeps every output.

    ``write_file`` is author code like the other hooks, so a failure is reported
    with the case index rather than escaping as a traceback.
    """
    cases_dir = problem_dir / CASES_DIRNAME
    cases_dir.mkdir(exist_ok=True)
    files: list[CaseFile] = []
    invalidated: list[str] = []
    for index, case in enumerate(cases):
        case_file = CaseFile(index, has_input)
        if case_file.input_name is not None:
            text = _render_input(case, index, source)
            path = problem_dir / case_file.input_name
            if _read_text(path) != text:
                path.write_text(text, encoding="utf-8")
                if (output := problem_dir / case_file.output_name).is_file():
                    output.unlink()
                    invalidated.append(case_file.output_name)
        files.append(case_file)
    _prune_case_files(cases_dir, len(cases))
    return files, invalidated


def _render_input(case: Any, index: int, source: str) -> str:
    buffer = io.StringIO()
    try:
        case.write_file(buffer)
    except Exception as error:
        raise CaseError(f"{source}: write_file() failed for case {index}: {error}") from error
    return buffer.getvalue()


def _read_text(path: Path) -> str | None:
    """The file's text, or None when it does not exist (or is not readable as text)."""
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None


def _prune_case_files(cases_dir: Path, count: int) -> list[str]:
    """Remove ``cases/{i}.in``/``.out`` left over from a larger previous run."""
    removed: list[str] = []
    for path in sorted(cases_dir.iterdir()):
        match = _CASE_FILE_RE.match(path.name)
        if match and int(match.group(1)) >= count and path.is_file():
            path.unlink()
            removed.append(f"{CASES_DIRNAME}/{path.name}")
    return removed


def require_model_files(problem_dir: Path, resolved: meta_mod.ResolvedMeta) -> list[str]:
    """Check the files ``init.yml`` will name actually exist; return their names."""
    required: list[str] = []
    if resolved.uses_checker:
        required.append(CHECKER_FILENAME)
    if resolved.uses_signature:
        required.extend((SIGNATURE_ENTRY, SIGNATURE_HEADER))
    for name in required:
        if not (problem_dir / name).is_file():
            raise CaseError(
                f"{problem_dir / name} not found: model {resolved.model!r} grades with "
                f"{_because(name)}"
            )
    return required


def _because(name: str) -> str:
    if name == CHECKER_FILENAME:
        return "a custom checker, and `init.yml` will declare `checker: checker.py`"
    if name == SIGNATURE_HEADER:
        return (
            "DMOJ's signature grader, and `init.yml` will declare "
            "`signature_grader: {entry: evaluator.cpp, header: signature.hpp}`"
        )
    return "DMOJ's signature grader, which compiles `evaluator.cpp` against the submission"


def _points_text(points: int | float) -> str:
    """YAML text for a points value, through PyYAML's own scalar emitter.

    ``f"{points:g}"`` would round (``100/3`` becomes ``33.3333``) and would emit
    ``1e+21``, which YAML reads back as a *string*.  The emitter round-trips both
    and is the same code that reads the file.
    """
    return yaml.safe_dump(points, default_flow_style=True).split("\n", 1)[0]


def _case_entry(case_file: CaseFile) -> str:
    pairs = []
    if case_file.input_name is not None:
        pairs.append(f"in: {case_file.input_name}")
    pairs.append(f"out: {case_file.output_name}")
    return "- {" + ", ".join(pairs) + "}"


def render_init(
    problem_name: str,
    resolved: meta_mod.ResolvedMeta,
    subtasks: Sequence[Subtask],
    membership: Sequence[Sequence[int]],
    case_files: Sequence[CaseFile],
) -> str:
    """Render the ``init.yml`` the judge loads.

    Driven by the resolved axes, never by the model *name*: ``checker:`` appears
    exactly when the checker axis is custom and ``signature_grader:`` exactly
    when the grader axis is signature (``dmoj/problem.py:200-210`` picks a
    grader by those keys, and by nothing else).
    """
    lines = [INIT_HEADER, f"archive: {problem_name}.zip"]
    if resolved.uses_checker:
        lines.append(f"checker: {CHECKER_FILENAME}")
    if resolved.uses_signature:
        lines.append(
            f"signature_grader: {{entry: {SIGNATURE_ENTRY}, header: {SIGNATURE_HEADER}}}"
        )
    lines.append("test_cases:")
    for subtask, indices in zip(subtasks, membership, strict=True):
        lines.append(f"- points: {_points_text(subtask.points)}")
        lines.append("  batched:")
        lines.extend(f"  {_case_entry(case_files[index])}" for index in indices)
        if subtask.dependencies:
            joined = ", ".join(str(dependency) for dependency in subtask.dependencies)
            lines.append(f"  dependencies: [{joined}]")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# cases
# ---------------------------------------------------------------------------


def add_cases_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("problem", help="problem directory to build cases for")
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="seed for the generator (default: the generator's own)",
    )


def run(args: argparse.Namespace) -> int:
    return run_cases(args.problem, seed=args.seed)


def run_cases(problem: str, *, seed: int | None = None) -> int:
    problem_dir = judges.resolve_problem(problem)
    # meta.yml first: the model decides whether cases even have input files.
    _, resolved = meta_mod.load(problem_dir)

    generator = load_generator(problem_dir, seed)
    source = str(problem_dir / GENERATOR_FILENAME)
    cases = read_cases(generator, source)
    subtasks = read_subtasks(generator, source)
    _check_model_supports(subtasks, resolved, problem_dir)

    # Classify before writing anything: a bad classifier must not leave a
    # half-written cases/ directory behind.
    membership = classify(subtasks, cases, source)
    case_files, invalidated = write_case_files(
        problem_dir, cases, has_input=not resolved.is_output_only, source=source
    )
    links = require_model_files(problem_dir, resolved)

    init = render_init(problem_dir.name, resolved, subtasks, membership, case_files)
    init_path = problem_dir / INIT_FILENAME
    init_path.write_text(init, encoding="utf-8")

    written = sum(1 for case_file in case_files if case_file.input_name is not None)
    print(f"{problem_dir.name}: {len(case_files)} cases, {written} input files -> {CASES_DIRNAME}/")
    for subtask, indices in zip(subtasks, membership, strict=True):
        detail = f"batch {subtask.number}: {_points_text(subtask.points)} pts, {len(indices)} cases"
        if subtask.dependencies:
            detail += f", after {', '.join(str(d) for d in subtask.dependencies)}"
        print(f"  {detail}")
    if links:
        print(f"  {', '.join(links)}")
    if invalidated:
        print(
            f"  discarded {len(invalidated)} stale expected output(s) whose input "
            f"changed: {', '.join(invalidated[:3])}"
            + (", ..." if len(invalidated) > 3 else "")
        )
    print(f"wrote {init_path}")
    return 0


def _check_model_supports(
    subtasks: Sequence[Subtask], resolved: meta_mod.ResolvedMeta, problem_dir: Path
) -> None:
    """Reject a generator whose batch structure contradicts its model.

    ``batch: single`` models pay once, all-or-nothing.  Several subtasks from
    such a generator still produce valid YAML -- several sibling batches -- which
    is the dangerous outcome: the file loads, and the scoring is silently no
    longer what the model says it is.
    """
    if len(subtasks) > 1 and not resolved.is_batched:
        numbers = ", ".join(str(subtask.number) for subtask in subtasks)
        raise CaseError(
            f"{problem_dir}: model {resolved.model!r} grades as a single batch, but "
            f"get_subtasks() returned {len(subtasks)} subtasks ({numbers}); emitting "
            f"them would turn an all-or-nothing problem into partial scoring without "
            f"saying so.  Use the 'batched' model (or `batch: subtasks` in meta.yml) "
            f"if partial scoring is intended"
        )


# ---------------------------------------------------------------------------
# archive
# ---------------------------------------------------------------------------


def add_archive_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("problem", help="problem directory whose init.yml declares the archive")


def run_archive_command(args: argparse.Namespace) -> int:
    return run_archive(args.problem)


def load_init(problem_dir: Path) -> dict[str, Any]:
    """Read the generated ``init.yml``."""
    path = problem_dir / INIT_FILENAME
    if not path.is_file():
        raise CaseError(
            f"{path} not found -- init.yml is generated; run "
            f"`problemsetting cases {problem_dir.name}` first"
        )
    try:
        document = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as error:
        raise CaseError(f"{path}: not valid YAML: {error}") from error
    if not isinstance(document, dict):
        raise CaseError(f"{path}: expected a mapping at the top level")
    return document


def _case_entries(document: dict[str, Any], source: str) -> list[dict[str, Any]]:
    """Every case mapping ``init.yml`` declares, flattened and validated, in order.

    One traversal of the emitted structure, so the two readers below --
    :func:`referenced_cases` (the archive's membership) and :func:`case_pairs`
    (``outputs``' work list) -- cannot disagree about what the file contains.  A
    hand-edited ``init.yml`` is the case both exist to catch, so a malformed entry
    is a ``CaseError`` naming the offending value rather than a case silently
    dropped from one list and not the other.
    """
    test_cases = document.get("test_cases")
    if not isinstance(test_cases, list) or not test_cases:
        raise CaseError(f"{source}: no test_cases -- run `problemsetting cases` first")
    entries: list[dict[str, Any]] = []
    for entry in test_cases:
        if not isinstance(entry, dict):
            raise CaseError(f"{source}: test_cases entries must be mappings, got {entry!r}")
        children = entry.get("batched")
        if children is None:
            children = [entry]
        if not isinstance(children, list):
            raise CaseError(f"{source}: `batched:` must be a list of cases")
        for child in children:
            if not isinstance(child, dict):
                raise CaseError(f"{source}: test case entries must be mappings, got {child!r}")
            entries.append(child)
    return entries


def _case_name(case: dict[str, Any], key: str, source: str) -> str | None:
    """One ``in:``/``out:`` value, or ``None`` when the case declares neither."""
    value = case.get(key)
    if value is None:
        return None
    if not isinstance(value, str):
        raise CaseError(f"{source}: `{key}:` must be a file name, got {value!r}")
    return value


def referenced_cases(document: dict[str, Any], source: str) -> list[str]:
    """Every ``in:``/``out:`` file ``init.yml`` names, in order, deduplicated.

    This is the archive's membership rule: a zip whose members are exactly the
    files the ``init.yml`` in the same directory references, so the two cannot
    drift apart.
    """
    names: list[str] = []
    for case in _case_entries(document, source):
        for key in ("in", "out"):
            if (name := _case_name(case, key, source)) is not None and name not in names:
                names.append(name)
    return names


def case_pairs(document: dict[str, Any], source: str) -> list[tuple[str | None, str]]:
    """Every ``(in, out)`` pair ``init.yml`` declares, in order, deduplicated by output.

    ``outputs`` runs one case per output file and needs the input that produced
    it; ``in`` is ``None`` for the output-only models, whose cases declare none
    (DMOJ supplies an empty sealed stdin, ``dmoj/problem.py:489-493``).  A repeated
    ``out`` -- a case selected by two subtasks -- is one expected output, so it is
    run once.
    """
    pairs: list[tuple[str | None, str]] = []
    seen: set[str] = set()
    for case in _case_entries(document, source):
        output = _case_name(case, "out", source)
        if output is None or output in seen:
            continue
        seen.add(output)
        pairs.append((_case_name(case, "in", source), output))
    return pairs


#: Fixed timestamp carried by every archive member: the ZIP epoch, 1980-01-01.
#: A real modification time is the one field that differs between two clones of
#: identical source, so pinning it is what makes the archive reproducible
#: (decision Q21; the plan's probe finding 3: ``ZipFile.write`` embeds the real
#: mtime, so two clones of one problem produced different archives).
ARCHIVE_DATE_TIME = (1980, 1, 1, 0, 0, 0)

#: Fixed Unix attributes for every member: a regular file with mode ``rw-r--r--``.
#: The alternative is the source file's own mode, which varies with the umask and
#: with how the checkout was made.
ARCHIVE_MEMBER_ATTR = 0o100644 << 16

#: Fixed deflate level.  ``zipfile``'s default (``-1``) means "whatever zlib's
#: default is", which is not a documented constant; naming the level makes the
#: archive bytes a function of the inputs alone.
ARCHIVE_COMPRESS_LEVEL = 9

#: Suffix of every committed checksum file (decision Q16).
CHECKSUM_SUFFIX = ".sha256sum"


def write_reproducible_zip(archive_path: Path, members: Sequence[tuple[str, Path]]) -> None:
    """Write ``(arcname, source)`` pairs as a zip that is byte-identical per input.

    Everything that would otherwise leak the build environment into the bytes is
    pinned (decision Q21):

    * each member's timestamp (:data:`ARCHIVE_DATE_TIME`, the ZIP epoch) --
      without this, a fresh clone's mtimes change the archive;
    * each member's attributes (:data:`ARCHIVE_MEMBER_ATTR`) -- otherwise the
      checkout's permissions show through;
    * the deflate level (:data:`ARCHIVE_COMPRESS_LEVEL`);
    * the member order, sorted by ``arcname``, so the caller's order (which comes
      from ``init.yml``) cannot leak into the bytes.

    ``ZipFile.write`` cannot be used for this: it takes the timestamp straight
    from the source file.  Members are streamed rather than buffered, because a
    case file can be megabytes and the archive is rebuilt wholesale on every run.
    """
    with zipfile.ZipFile(
        archive_path, "w", zipfile.ZIP_DEFLATED, compresslevel=ARCHIVE_COMPRESS_LEVEL
    ) as archive:
        for arcname, source in sorted(members, key=lambda member: member[0]):
            info = zipfile.ZipInfo(arcname, date_time=ARCHIVE_DATE_TIME)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.compress_level = ARCHIVE_COMPRESS_LEVEL
            info.create_system = 3  # Unix: the attributes above are a Unix mode.
            info.external_attr = ARCHIVE_MEMBER_ATTR
            info.file_size = source.stat().st_size
            with archive.open(info, "w") as destination, source.open("rb") as origin:
                shutil.copyfileobj(origin, destination, length=1 << 20)


def sha256_file(path: Path) -> str:
    """The SHA-256 of a file's bytes, as lowercase hexadecimal.

    Streamed by ``hashlib.file_digest`` rather than read whole: a case file can be
    megabytes, and this runs once per member on every archive.
    """
    with path.open("rb") as handle:
        return hashlib.file_digest(handle, "sha256").hexdigest()


def archive_checksum_name(archive_name: str) -> str:
    """The checksum of the archive bytes, named after the *declared* archive.

    Derived from ``init.yml``'s ``archive:`` value rather than a literal, so a
    problem whose archive is named anything else still gets a correctly named
    checksum beside it (decision Q15 and the plan's open item on
    ``test_cases.zip``).
    """
    return f"{archive_name}{CHECKSUM_SUFFIX}"


def case_data_checksum_name(archive_name: str) -> str:
    """The checksum of the case *data*, named after the declared archive."""
    return f"{archive_name}.cases{CHECKSUM_SUFFIX}"


def case_data_manifest(
    problem_dir: Path, names: Sequence[str], document: Mapping[str, Any]
) -> str:
    """A digest of the *case data*, not of how it was packaged.

    Files are listed first, one ``sha256sum`` line each, sorted by name, so the
    file verifies with ``sha256sum -c`` from the problem directory and is itself
    reproducible.

    The grading structure is appended as a ``#`` comment line: the points, batch
    membership and dependencies are part of what a generator produces, and a
    generator retuned only in *how it groups cases* leaves every case file -- and
    therefore the archive -- byte-identical, so neither checksum would move
    without this.  ``sha256sum -c`` ignores comment lines, so the file still
    verifies.  ``document`` is required rather than optional: the structure line
    is what gives this digest its teeth, so a caller cannot quietly produce a
    weaker one.

    The declared *archive filename* is excluded from the structure: it is how the
    case data is packaged, which is the one thing this second checksum exists to
    be independent of (decision Q15).
    """
    lines = [f"{sha256_file(problem_dir / name)}  {name}" for name in sorted(names)]
    structure = {key: value for key, value in document.items() if key != "archive"}
    # Canonical, sorted-key JSON: the manifest must not depend on PyYAML's mapping
    # order (it preserves insertion order, which is stable today but is not a
    # property this checksum should rely on).
    canonical = json.dumps(structure, sort_keys=True, separators=(",", ":"))
    lines.append(f"# {sha256_of(canonical)}  init.yml")
    return "".join(f"{line}\n" for line in lines)


def sha256_of(text: str) -> str:
    """The SHA-256 of a UTF-8 string's bytes."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def write_checksums(
    problem_dir: Path, archive_name: str, names: Sequence[str], document: Mapping[str, Any]
) -> tuple[Path, Path]:
    """Write both committed checksums beside the archive; return their paths.

    The first ties the packaged artifact to the committed source; the second
    records the cases independently of how they were packaged (decision Q15).

    Written only after a successful archive build, so each describes the last
    *successful* build.  A later failure that discards the archive -- ``outputs``
    removes it whenever a rebuild breaks, because DMOJ reads answers out of it --
    therefore leaves these two files describing the archive that used to be
    there.  That is deliberate: they are the committed record of what the
    generator produced, and deleting them on a failure would lose the evidence
    ``regenerate --check`` (decision Q22) compares against.
    """
    archive_checksum = problem_dir / archive_checksum_name(archive_name)
    case_checksum = problem_dir / case_data_checksum_name(archive_name)
    archive_checksum.write_text(
        f"{sha256_file(problem_dir / archive_name)}  {archive_name}\n", encoding="utf-8"
    )
    case_checksum.write_text(
        case_data_manifest(problem_dir, names, document), encoding="utf-8"
    )
    return archive_checksum, case_checksum


def run_archive(problem: str) -> int:
    problem_dir = judges.resolve_problem(problem)
    init_path = problem_dir / INIT_FILENAME
    document = load_init(problem_dir)
    archive_name = document.get("archive")
    if not isinstance(archive_name, str) or not archive_name:
        raise CaseError(
            f"{init_path}: no `archive:` filename declared; the judge needs one to find "
            f"the bundled cases"
        )
    names = referenced_cases(document, str(init_path))

    missing = [name for name in names if not (problem_dir / name).is_file()]
    if missing:
        # A zip missing expected outputs would be graded as if those cases had
        # no answer at all, so refuse rather than ship a half archive.
        raise CaseError(
            f"{len(missing)} file(s) referenced by {init_path} are missing, e.g. "
            f"{missing[0]}; run `problemsetting outputs {problem_dir.name}` (or "
            f"`problemsetting build {problem_dir.name}`) after generating cases"
        )

    archive_path = problem_dir / archive_name
    write_reproducible_zip(archive_path, [(name, problem_dir / name) for name in names])
    archive_checksum, case_checksum = write_checksums(
        problem_dir, archive_name, names, document
    )
    print(f"{archive_path}: {len(names)} members")
    print(f"{archive_checksum}: sha256 of the archive")
    print(f"{case_checksum}: sha256 of the case data")
    return 0


# ---------------------------------------------------------------------------
# build
# ---------------------------------------------------------------------------


def add_build_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("problem", help="problem directory to build end to end")
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="seed for the generator (default: the generator's own)",
    )


def run_build_command(args: argparse.Namespace) -> int:
    return run_build(args.problem, seed=args.seed)


def run_build(problem: str, *, seed: int | None = None) -> int:
    """``cases`` → ``outputs`` → ``archive``, in that order and by name.

    The steps are the same code paths the standalone subcommands use, so
    ``build`` cannot drift from them.
    """
    print(f"==> cases {problem}")
    if (status := run_cases(problem, seed=seed)) != 0:
        return status

    print(f"==> outputs {problem}")
    if (status := _run_outputs_step(problem)) != 0:
        return status

    print(f"==> archive {problem}")
    return run_archive(problem)


def _run_outputs_step(problem: str) -> int:
    """Run the ``outputs`` subcommand's implementation, not a re-parsed CLI call.

    Imported here rather than at module level: ``outputs`` imports this module for
    :func:`load_init` / :func:`case_pairs`, so a top-level import would be
    circular.  Calling :func:`problemsetting.outputs.run_outputs` directly keeps
    ``build`` on the same code path as the standalone subcommand.
    """
    from . import outputs

    return outputs.run_outputs(problem)


register(
    Command(
        name="cases",
        help="generate cases/*.in and init.yml from the problem's generator.py",
        add_arguments=add_cases_arguments,
        run=run,
    )
)

register(
    Command(
        name="archive",
        help="zip the cases init.yml references into the declared archive",
        add_arguments=add_archive_arguments,
        run=run_archive_command,
    )
)

register(
    Command(
        name="build",
        help="run cases, outputs and archive in order",
        add_arguments=add_build_arguments,
        run=run_build_command,
    )
)
