"""``cases``, ``archive`` and ``build``: generator → ``cases/*.in`` + ``init.yml`` → ``.zip``.

The generator is the author's code (``<problem>/generator.py``); this module is
the fixed half of the contract (decision Q22).  The protocol:

* ``TestCase.check()`` / ``TestCase.write_file(f)`` -- the case validates itself
  and writes its own input format.  The *toolkit* chooses file names.
* ``Generator.get_cases()`` -- the ordered case list.  Position is file number:
  case ``i`` is ``cases/{i}.in`` / ``cases/{i}.out``.
* ``Generator.get_subtasks()`` -- ``(points, check_fn)`` per subtask, with an
  optional third element: a list of 1-based prerequisite batch numbers, which
  becomes DMOJ's per-batch ``dependencies:`` key.  Two-element tuples keep
  working unchanged.

A case belongs to a subtask when ``check_fn(case)`` is truthy, so a case may be
in several batches -- that is the "all-accepting final subtask" convention the
``standard``/``batched`` templates rely on.

Two things the emitted ``init.yml`` gets from ``meta.yml`` instead of from the
generator (both are properties of the *model*, resolved by :mod:`meta`):

* ``submission: text`` models (the two output-only ones) have **no input**:
  DMOJ's ``TestCase._make_input_data_io()`` falls back to a sealed empty
  ``MemoryIO`` when a case declares no ``in:`` (``dmoj/problem.py:489-493``), so
  those cases declare only ``out:`` and their ``write_file`` is never called.
* a custom-checker model needs ``checker.py`` on disk, and a signature model
  needs ``evaluator.cpp`` + ``signature.hpp``; both are named in ``init.yml``
  and both are checked here, so a dangling reference is an authoring error
  instead of a judge-side failure inside the container.

Batches are validated the way DMOJ validates them
(``dmoj/problem.py:325-337``): dependencies must be positive integers strictly
less than the batch number that declares them, nested batches are rejected
outright (``InvalidInitException('nested batches')``), and a batch that selects
no case is refused here because an empty ``batched:`` key is YAML ``null`` and
the judge iterates that value.
"""

from __future__ import annotations

import argparse
import dataclasses
import io
import re
import types
import zipfile
from collections.abc import Callable, Iterable, Sequence
from pathlib import Path
from typing import Any, Protocol

import yaml

from . import commands
from . import meta as meta_mod
from .commands import Command, register
from .errors import CaseError, ProblemsettingError

GENERATOR_FILENAME = "generator.py"
INIT_FILENAME = "init.yml"
CASES_DIRNAME = "cases"

#: The standard checker/signature file names (ticket 11 fixes these names; the
#: judge accepts others, but a problem that renames them must be checked here
#: rather than emitting a reference to a file that does not exist).
CHECKER_FILENAME = "checker.py"
SIGNATURE_HEADER = "signature.hpp"
SIGNATURE_ENTRY = "evaluator.cpp"

#: First line of every generated ``init.yml``.  It is a build artifact: the
#: sources of truth are ``meta.yml`` (model/limits) and ``generator.py`` (cases).
INIT_HEADER = (
    "# Generated by `problemsetting cases` -- edit meta.yml and generator.py, not this file."
)

#: Leftover case files from a previous, larger run are removed: a stale
#: ``cases/{i}.out`` is the one failure mode this toolkit must never leave
#: behind, because the judge would grade it as the expected answer.
_CASE_FILE_RE = re.compile(r"(\d+)\.(?:in|out)\Z")


class GeneratorLike(Protocol):
    """The slice of the author's ``Generator`` this module calls.

    Structural, not inherited: a generator is author code loaded from a file, so
    there is no base class to subclass and nothing to enforce at runtime -- only
    the two calls below, which :func:`load_generator` and :func:`read_cases` /
    :func:`read_subtasks` check for by hand.
    """

    def get_cases(self) -> Sequence[Any]: ...

    def get_subtasks(self) -> Sequence[Any]: ...


# ---------------------------------------------------------------------------
# The generator: loading it, and reading the protocol out of it
# ---------------------------------------------------------------------------


def load_generator(problem_dir: Path, seed: int | None = None) -> GeneratorLike:
    """Compile and run ``<problem_dir>/generator.py``; instantiate its ``Generator``.

    The file is *compiled from source each time*, never imported through
    ``importlib``'s file loader: that loader honours a sibling ``__pycache__``
    entry whenever the bytecode's recorded (mtime, size) still matches, so a
    same-second, same-length edit would silently run the previous generator --
    and the cases would then be built from code the author is no longer looking
    at.  Compiling costs nothing at this scale and removes the whole class of
    "why did my change not apply" bugs.
    """
    path = problem_dir / GENERATOR_FILENAME
    if not path.is_file():
        raise CaseError(
            f"{path} not found -- every problem needs a generator.py; the model "
            f"template ships a complete one to start from"
        )
    try:
        code = compile(path.read_text(encoding="utf-8"), str(path), "exec")
    except (OSError, UnicodeDecodeError, SyntaxError) as error:
        raise CaseError(f"{path}: {error}") from error

    module = types.ModuleType(f"_problemsetting_generator_{problem_dir.name}")
    module.__file__ = str(path)
    try:
        exec(code, module.__dict__)
    except Exception as error:  # author code: report it without the traceback
        raise CaseError(f"{path}: {error}") from error

    factory = getattr(module, "Generator", None)
    if factory is None:
        raise CaseError(
            f"{path}: no `Generator` class -- the toolkit instantiates "
            f"`Generator()` and calls `get_cases()` and `get_subtasks()` on it"
        )
    try:
        return factory() if seed is None else factory(seed)
    except Exception as error:
        raise CaseError(f"{path}: Generator(...) failed: {error}") from error


@dataclasses.dataclass(frozen=True)
class Subtask:
    """One entry of ``Generator.get_subtasks()`` after validation."""

    #: 1-based batch number, i.e. the order in ``get_subtasks()``.
    number: int
    points: int | float
    check: Callable[[Any], Any]
    #: Prerequisite batch numbers; empty when the subtask declares none.
    dependencies: tuple[int, ...]


def require_sequence(value: Any, source: str, expectation: str) -> Sequence[Any]:
    """Check ``value`` is a list-shaped result; ``expectation`` names what it should be.

    ``str``/``bytes`` are sequences too, and a generator that returns
    ``"cases"`` by mistake would otherwise be read as three one-character cases.
    """
    if isinstance(value, (str, bytes)) or not isinstance(value, Sequence):
        raise CaseError(f"{source}: {expectation}, not {type(value).__name__}")
    return value


def read_cases(generator: GeneratorLike, source: str) -> list[Any]:
    """``generator.get_cases()``, validated as a non-empty ordered sequence."""
    try:
        cases = generator.get_cases()
    except Exception as error:  # the author's ``check()`` runs here
        raise CaseError(f"{source}: get_cases() failed: {error}") from error
    require_sequence(cases, source, "get_cases() must return a list of cases")
    if not cases:
        raise CaseError(f"{source}: get_cases() returned no cases; there is nothing to grade")
    for index, case in enumerate(cases):
        for method in ("check", "write_file"):
            if not callable(getattr(case, method, None)):
                raise CaseError(
                    f"{source}: case {index} ({type(case).__name__}) has no "
                    f"{method}() method; the toolkit only requires those two"
                )
    return list(cases)


def read_subtasks(generator: GeneratorLike, source: str) -> list[Subtask]:
    """``generator.get_subtasks()``, validated against DMOJ's batch rules.

    Every rule here exists because the alternative is an ``init.yml`` the judge
    rejects at load time with a message about the file's shape rather than about
    the generator line that caused it.
    """
    try:
        entries = generator.get_subtasks()
    except Exception as error:
        raise CaseError(f"{source}: get_subtasks() failed: {error}") from error
    require_sequence(entries, source, "get_subtasks() must return a list of (points, check) entries")
    if not entries:
        raise CaseError(
            f"{source}: get_subtasks() returned nothing; a problem with no subtasks "
            f"has nothing to grade"
        )

    subtasks: list[Subtask] = []
    for index, entry in enumerate(entries, start=1):
        subtasks.append(_read_subtask(entry, index, source, len(entries)))
    return subtasks


def _read_subtask(entry: Any, number: int, source: str, total: int) -> Subtask:
    where = f"subtask {number} of {total}" if total > 1 else "the subtask"
    require_sequence(entry, source, f"{where} must be a (points, check) pair")
    if len(entry) not in (2, 3):
        raise CaseError(
            f"{source}: {where} has {len(entry)} elements; expected (points, check) "
            f"or (points, check, dependencies)"
        )
    if not isinstance(entry[1], Callable):
        if isinstance(entry[1], (list, tuple)):
            # The shape this rejects: (points, [inner, batches]).
            raise CaseError(
                f"{source}: {where} holds a nested subtask list where the classifier "
                f"should be; DMOJ rejects nested batches ('nested batches'), so "
                f"subtasks must be a flat list of (points, check) pairs"
            )
        raise CaseError(
            f"{source}: {where} has a non-callable classifier ({entry[1]!r}); the second "
            f"element is `check_fn(case)`, called once per case"
        )

    points = entry[0]
    if isinstance(points, bool) or not isinstance(points, (int, float)):
        raise CaseError(
            f"{source}: {where} has non-numeric points ({points!r}); points are the "
            f"batch's share of the score"
        )
    if points <= 0:
        raise CaseError(
            f"{source}: {where} is worth {points} points; a batch worth no points can "
            f"never score"
        )

    dependencies = _read_dependencies(entry[2] if len(entry) == 3 else [], number, where, source)
    return Subtask(number, points, entry[1], dependencies)


def _read_dependencies(raw: Any, number: int, where: str, source: str) -> tuple[int, ...]:
    if raw is None:
        return ()
    require_sequence(
        raw,
        source,
        f"{where} declares dependencies {raw!r}; the third element must be a "
        f"list of 1-based batch numbers, e.g. [1]",
    )
    dependencies: list[int] = []
    for value in raw:
        if isinstance(value, bool) or not isinstance(value, int):
            raise CaseError(
                f"{source}: {where} declares dependency {value!r}; dependencies must be "
                f"positive integers naming earlier batches"
            )
        if value < 1:
            raise CaseError(
                f"{source}: {where} depends on batch {value}; DMOJ requires batches to "
                f"be positive integers ('dependencies must be positive integers')"
            )
        if value >= number:
            raise CaseError(
                f"{source}: {where} depends on batch {value}, which is not an earlier "
                f"batch; DMOJ requires each dependency to be less than the batch that "
                f"declares it ('dependencies depends on non-earlier batch')"
            )
        dependencies.append(value)
    # Sorted and deduplicated: the judge compares dependencies as a set, so this
    # only makes the emitted file canonical.
    return tuple(sorted(set(dependencies)))


def classify(subtasks: Iterable[Subtask], cases: Sequence[Any], source: str) -> list[list[int]]:
    """Case indices per subtask, in case order.

    Two rules, both of which exist because the alternative is an ``init.yml``
    the judge chokes on at load time instead of an error naming the generator:

    * ``check_fn`` is author code, so a classifier that raises is reported with
      the batch and the case it raised on;
    * a batch that selects no case is refused.  DMOJ branches on
      ``'batched' in case_config`` and then iterates the value
      (``dmoj/problem.py:227-235``), so an empty ``batched:`` key -- YAML
      ``null`` -- fails with ``TypeError: 'NoneType' object is not iterable``.
    """
    cases = list(cases)
    membership: list[list[int]] = []
    for subtask in subtasks:
        selected: list[int] = []
        for index, case in enumerate(cases):
            try:
                matched = subtask.check(case)
            except Exception as error:
                raise CaseError(
                    f"{source}: the classifier of batch {subtask.number} raised on case "
                    f"{index}: {error}"
                ) from error
            if matched:
                selected.append(index)
        if not selected:
            raise CaseError(
                f"{source}: the classifier of batch {subtask.number} selects none of the "
                f"{len(cases)} cases; a batch with no cases cannot be emitted (DMOJ would "
                f"fail to load the problem).  Every batch needs at least one case -- the "
                f"usual shape is an all-accepting last batch that absorbs the rest"
            )
        membership.append(selected)
    return membership


# ---------------------------------------------------------------------------


@dataclasses.dataclass(frozen=True)
class CaseFile:
    """Where one case's files live, relative to the problem directory."""

    index: int
    has_input: bool

    @property
    def input_name(self) -> str | None:
        return f"{CASES_DIRNAME}/{self.index}.in" if self.has_input else None

    @property
    def output_name(self) -> str:
        return f"{CASES_DIRNAME}/{self.index}.out"


def write_case_files(
    problem_dir: Path, cases: Sequence[Any], *, has_input: bool, source: str
) -> tuple[list[CaseFile], list[str]]:
    """Write each case's input; return its file names and the outputs invalidated.

    Expected outputs are *not* produced here: they are ``outputs``' job (ticket
    03), because they require running the model solution.  But an input that
    *changed* invalidates its sibling ``.out``, which is deleted so that the pair
    cannot silently disagree.  A stale ``.out`` is the one failure mode this
    toolkit must never ship, because the judge would grade it as the expected
    answer.  An input that is byte-identical is left alone, so re-running with no
    change keeps every output.

    ``write_file`` is author code like the other hooks, so a failure is reported
    with the case index rather than escaping as a traceback.
    """
    cases_dir = problem_dir / CASES_DIRNAME
    cases_dir.mkdir(exist_ok=True)
    files: list[CaseFile] = []
    invalidated: list[str] = []
    for index, case in enumerate(cases):
        case_file = CaseFile(index, has_input)
        if case_file.input_name is not None:
            text = _render_input(case, index, source)
            path = problem_dir / case_file.input_name
            if _read_text(path) != text:
                path.write_text(text, encoding="utf-8")
                if (output := problem_dir / case_file.output_name).is_file():
                    output.unlink()
                    invalidated.append(case_file.output_name)
        files.append(case_file)
    _prune_case_files(cases_dir, len(cases))
    return files, invalidated


def _render_input(case: Any, index: int, source: str) -> str:
    buffer = io.StringIO()
    try:
        case.write_file(buffer)
    except Exception as error:
        raise CaseError(f"{source}: write_file() failed for case {index}: {error}") from error
    return buffer.getvalue()


def _read_text(path: Path) -> str | None:
    """The file's text, or None when it does not exist (or is not readable as text)."""
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return None


def _prune_case_files(cases_dir: Path, count: int) -> list[str]:
    """Remove ``cases/{i}.in``/``.out`` left over from a larger previous run."""
    removed: list[str] = []
    for path in sorted(cases_dir.iterdir()):
        match = _CASE_FILE_RE.match(path.name)
        if match and int(match.group(1)) >= count and path.is_file():
            path.unlink()
            removed.append(f"{CASES_DIRNAME}/{path.name}")
    return removed


def require_model_files(problem_dir: Path, resolved: meta_mod.ResolvedMeta) -> list[str]:
    """Check the files ``init.yml`` will name actually exist; return their names."""
    required: list[str] = []
    if resolved.uses_checker:
        required.append(CHECKER_FILENAME)
    if resolved.uses_signature:
        required.extend((SIGNATURE_ENTRY, SIGNATURE_HEADER))
    for name in required:
        if not (problem_dir / name).is_file():
            raise CaseError(
                f"{problem_dir / name} not found: model {resolved.model!r} grades with "
                f"{_because(name)}"
            )
    return required


def _because(name: str) -> str:
    if name == CHECKER_FILENAME:
        return "a custom checker, and `init.yml` will declare `checker: checker.py`"
    if name == SIGNATURE_HEADER:
        return (
            "DMOJ's signature grader, and `init.yml` will declare "
            "`signature_grader: {entry: evaluator.cpp, header: signature.hpp}`"
        )
    return "DMOJ's signature grader, which compiles `evaluator.cpp` against the submission"


def _points_text(points: int | float) -> str:
    """YAML text for a points value, through PyYAML's own scalar emitter.

    ``f"{points:g}"`` would round (``100/3`` becomes ``33.3333``) and would emit
    ``1e+21``, which YAML reads back as a *string*.  The emitter round-trips both
    and is the same code that reads the file.
    """
    return yaml.safe_dump(points, default_flow_style=True).split("\n", 1)[0]


def _case_entry(case_file: CaseFile) -> str:
    pairs = []
    if case_file.input_name is not None:
        pairs.append(f"in: {case_file.input_name}")
    pairs.append(f"out: {case_file.output_name}")
    return "- {" + ", ".join(pairs) + "}"


def render_init(
    problem_name: str,
    resolved: meta_mod.ResolvedMeta,
    subtasks: Sequence[Subtask],
    membership: Sequence[Sequence[int]],
    case_files: Sequence[CaseFile],
) -> str:
    """Render the ``init.yml`` the judge loads.

    Driven by the resolved axes, never by the model *name*: ``checker:`` appears
    exactly when the checker axis is custom and ``signature_grader:`` exactly
    when the grader axis is signature (``dmoj/problem.py:200-210`` picks a
    grader by those keys, and by nothing else).
    """
    lines = [INIT_HEADER, f"archive: {problem_name}.zip"]
    if resolved.uses_checker:
        lines.append(f"checker: {CHECKER_FILENAME}")
    if resolved.uses_signature:
        lines.append(
            f"signature_grader: {{entry: {SIGNATURE_ENTRY}, header: {SIGNATURE_HEADER}}}"
        )
    lines.append("test_cases:")
    for subtask, indices in zip(subtasks, membership, strict=True):
        lines.append(f"- points: {_points_text(subtask.points)}")
        lines.append("  batched:")
        lines.extend(f"  {_case_entry(case_files[index])}" for index in indices)
        if subtask.dependencies:
            joined = ", ".join(str(dependency) for dependency in subtask.dependencies)
            lines.append(f"  dependencies: [{joined}]")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# cases
# ---------------------------------------------------------------------------


def add_cases_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("problem", help="problem directory to build cases for")
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="seed for the generator (default: the generator's own)",
    )


def run(args: argparse.Namespace) -> int:
    return run_cases(args.problem, seed=args.seed)


def run_cases(problem: str, *, seed: int | None = None) -> int:
    problem_dir = Path.cwd() / problem
    # meta.yml first: the model decides whether cases even have input files.
    _, resolved = meta_mod.load(problem_dir)

    generator = load_generator(problem_dir, seed)
    source = str(problem_dir / GENERATOR_FILENAME)
    cases = read_cases(generator, source)
    subtasks = read_subtasks(generator, source)
    _check_model_supports(subtasks, resolved, problem_dir)

    # Classify before writing anything: a bad classifier must not leave a
    # half-written cases/ directory behind.
    membership = classify(subtasks, cases, source)
    case_files, invalidated = write_case_files(
        problem_dir, cases, has_input=not resolved.is_output_only, source=source
    )
    links = require_model_files(problem_dir, resolved)

    init = render_init(problem_dir.name, resolved, subtasks, membership, case_files)
    init_path = problem_dir / INIT_FILENAME
    init_path.write_text(init, encoding="utf-8")

    written = sum(1 for case_file in case_files if case_file.input_name is not None)
    print(f"{problem_dir.name}: {len(case_files)} cases, {written} input files -> {CASES_DIRNAME}/")
    for subtask, indices in zip(subtasks, membership, strict=True):
        detail = f"batch {subtask.number}: {_points_text(subtask.points)} pts, {len(indices)} cases"
        if subtask.dependencies:
            detail += f", after {', '.join(str(d) for d in subtask.dependencies)}"
        print(f"  {detail}")
    if links:
        print(f"  {', '.join(links)}")
    if invalidated:
        print(
            f"  discarded {len(invalidated)} stale expected output(s) whose input "
            f"changed: {', '.join(invalidated[:3])}"
            + (", ..." if len(invalidated) > 3 else "")
        )
    print(f"wrote {init_path}")
    return 0


def _check_model_supports(
    subtasks: Sequence[Subtask], resolved: meta_mod.ResolvedMeta, problem_dir: Path
) -> None:
    """Reject a generator whose batch structure contradicts its model.

    ``batch: single`` models pay once, all-or-nothing.  Several subtasks from
    such a generator still produce valid YAML -- several sibling batches -- which
    is the dangerous outcome: the file loads, and the scoring is silently no
    longer what the model says it is.
    """
    if len(subtasks) > 1 and not resolved.is_batched:
        numbers = ", ".join(str(subtask.number) for subtask in subtasks)
        raise CaseError(
            f"{problem_dir}: model {resolved.model!r} grades as a single batch, but "
            f"get_subtasks() returned {len(subtasks)} subtasks ({numbers}); emitting "
            f"them would turn an all-or-nothing problem into partial scoring without "
            f"saying so.  Use the 'batched' model (or `batch: subtasks` in meta.yml) "
            f"if partial scoring is intended"
        )


# ---------------------------------------------------------------------------
# archive
# ---------------------------------------------------------------------------


def add_archive_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("problem", help="problem directory whose init.yml declares the archive")


def run_archive_command(args: argparse.Namespace) -> int:
    return run_archive(args.problem)


def load_init(problem_dir: Path) -> dict[str, Any]:
    """Read the generated ``init.yml``."""
    path = problem_dir / INIT_FILENAME
    if not path.is_file():
        raise CaseError(
            f"{path} not found -- init.yml is generated; run "
            f"`problemsetting cases {problem_dir.name}` first"
        )
    try:
        document = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as error:
        raise CaseError(f"{path}: not valid YAML: {error}") from error
    if not isinstance(document, dict):
        raise CaseError(f"{path}: expected a mapping at the top level")
    return document


def referenced_cases(document: dict[str, Any], source: str) -> list[str]:
    """Every ``in:``/``out:`` file ``init.yml`` names, in order, deduplicated.

    This is the archive's membership rule: a zip whose members are exactly the
    files the ``init.yml`` in the same directory references, so the two cannot
    drift apart.
    """
    test_cases = document.get("test_cases")
    if not isinstance(test_cases, list) or not test_cases:
        raise CaseError(f"{source}: no test_cases -- run `problemsetting cases` first")
    names: list[str] = []
    for entry in test_cases:
        if not isinstance(entry, dict):
            raise CaseError(f"{source}: test_cases entries must be mappings, got {entry!r}")
        children = entry.get("batched")
        if children is None:
            children = [entry]
        if not isinstance(children, list):
            raise CaseError(f"{source}: `batched:` must be a list of cases")
        for child in children:
            if not isinstance(child, dict):
                raise CaseError(f"{source}: test case entries must be mappings, got {child!r}")
            for key in ("in", "out"):
                value = child.get(key)
                if value is None:
                    continue
                if not isinstance(value, str):
                    raise CaseError(f"{source}: `{key}:` must be a file name, got {value!r}")
                if value not in names:
                    names.append(value)
    return names


def run_archive(problem: str) -> int:
    problem_dir = Path.cwd() / problem
    init_path = problem_dir / INIT_FILENAME
    document = load_init(problem_dir)
    archive_name = document.get("archive")
    if not isinstance(archive_name, str) or not archive_name:
        raise CaseError(
            f"{init_path}: no `archive:` filename declared; the judge needs one to find "
            f"the bundled cases"
        )
    names = referenced_cases(document, str(init_path))

    missing = [name for name in names if not (problem_dir / name).is_file()]
    if missing:
        # A zip missing expected outputs would be graded as if those cases had
        # no answer at all, so refuse rather than ship a half archive.
        raise CaseError(
            f"{len(missing)} file(s) referenced by {init_path} are missing, e.g. "
            f"{missing[0]}; run `problemsetting outputs {problem_dir.name}` (or "
            f"`problemsetting build {problem_dir.name}`) after generating cases"
        )

    archive_path = problem_dir / archive_name
    with zipfile.ZipFile(archive_path, "w", zipfile.ZIP_DEFLATED) as archive:
        for name in names:
            archive.write(problem_dir / name, arcname=name)
    print(f"{archive_path}: {len(names)} members")
    return 0


# ---------------------------------------------------------------------------
# build
# ---------------------------------------------------------------------------


def add_build_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("problem", help="problem directory to build end to end")
    parser.add_argument(
        "--seed",
        type=int,
        default=None,
        help="seed for the generator (default: the generator's own)",
    )


def run_build_command(args: argparse.Namespace) -> int:
    return run_build(args.problem, seed=args.seed)


def run_build(problem: str, *, seed: int | None = None) -> int:
    """``cases`` → ``outputs`` → ``archive``, in that order and by name.

    The steps are the same code paths the standalone subcommands use, so
    ``build`` cannot drift from them.
    """
    print(f"==> cases {problem}")
    if (status := run_cases(problem, seed=seed)) != 0:
        return status

    print(f"==> outputs {problem}")
    if (status := _run_outputs_step(problem)) != 0:
        return status

    print(f"==> archive {problem}")
    return run_archive(problem)


def _run_outputs_step(problem: str) -> int:
    """Run the ``outputs`` subcommand, or fail saying exactly what is missing.

    ``outputs`` is ticket 03.  Until it lands, ``build`` must stop after
    ``cases`` and say so: silently skipping the step would leave a problem whose
    ``init.yml`` references expected outputs that do not exist.
    """
    if "outputs" not in commands.COMMANDS:
        raise ProblemsettingError(
            f"this build of the toolkit has no `outputs` step yet (ticket 03), so "
            f"`build` cannot finish {problem!r}: cases and init.yml are written, but "
            f"there are no expected `cases/*.out` files for `archive` to bundle.  Run "
            f"`problemsetting cases {problem}` and `problemsetting archive {problem}` "
            f"separately once the outputs are in place"
        )
    # Imported here, not at module level: ``cli`` imports every subcommand module
    # including this one, so a top-level import would be circular.
    from . import cli

    return cli.main(["outputs", problem])


register(
    Command(
        name="cases",
        help="generate cases/*.in and init.yml from the problem's generator.py",
        add_arguments=add_cases_arguments,
        run=run,
    )
)

register(
    Command(
        name="archive",
        help="zip the cases init.yml references into the declared archive",
        add_arguments=add_archive_arguments,
        run=run_archive_command,
    )
)

register(
    Command(
        name="build",
        help="run cases, outputs and archive in order",
        add_arguments=add_build_arguments,
        run=run_build_command,
    )
)
